name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  set-environment:
    name: Set environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}

    steps:
      - name: Set environment
        id: set-env
        uses: AdPro-B14/heymart-store/.github/actions/set-environment@dev
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    needs: [set-environment]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-store-${{ needs.set-environment.outputs.environment }} .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-store-${{ needs.set-environment.outputs.environment }}

      - name: Deploy ${{ needs.set-environment.outputs.environment }}
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'heymart-store-${{ needs.set-environment.outputs.environment }}'
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-store-${{ needs.set-environment.outputs.environment }}
          region: asia-southeast2
          timeout: 15m
          env_vars: |
            PG_HOST=${{ secrets.PG_HOST }}
            PG_HOST_DEV=${{ secrets.PG_HOST_DEV }}
            PG_HOST_STAGING=${{ secrets.PG_HOST_STAGING }}
            PG_USERNAME=${{ secrets.PG_USERNAME }}
            PG_PASSWORD=${{ secrets.PG_PASSWORD }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_EXPIRE_DURATION=${{ secrets.JWT_EXPIRE_DURATION }}
            GATEWAY_TOKEN=${{ secrets.GATEWAY_TOKEN }}
            ENVIRONMENT_PROFILE=${{ needs.set-environment.outputs.environment }}
            GATEWAY_URL=${{ secrets.GATEWAY_URL }}
            GATEWAY_URL_DEV=${{ secrets.GATEWAY_URL_DEV }}
            GATEWAY_URL_STAGING=${{ secrets.GATEWAY_URL_STAGING }}