name: Continous Integration (CI)

on:
  push:
  pull_request:

env:
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_HOST_DEV: ${{ secrets.PG_HOST_DEV }}
  PG_HOST_STAGING: ${{ secrets.PG_HOST_STAGING }}
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_EXPIRE_DURATION: ${{ secrets.JWT_EXPIRE_DURATION }}
  GATEWAY_TOKEN: ${{ secrets.GATEWAY_TOKEN }}
  GATEWAY_URL: ${{ secrets.GATEWAY_URL }}
  GATEWAY_URL_DEV: ${{ secrets.GATEWAY_URL_DEV }}
  GATEWAY_URL_STAGING: ${{ secrets.GATEWAY_URL_STAGING }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:

      - name: Check out the git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Set gradlew as executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test